# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_main_VisPy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_17.addWidget(self.pushButton, 1, 0, 1, 1)
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalScrollBar_Image_Imin = QtWidgets.QScrollBar(self.groupBox_28)
        self.horizontalScrollBar_Image_Imin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Image_Imin.setObjectName("horizontalScrollBar_Image_Imin")
        self.verticalLayout_26.addWidget(self.horizontalScrollBar_Image_Imin)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_33 = QtWidgets.QLabel(self.groupBox_28)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_42.addWidget(self.label_33)
        self.label_38 = QtWidgets.QLabel(self.groupBox_28)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_42.addWidget(self.label_38)
        self.verticalLayout_26.addLayout(self.horizontalLayout_42)
        self.gridLayout_16.addLayout(self.verticalLayout_26, 0, 0, 1, 1)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalScrollBar_Image_Imax = QtWidgets.QScrollBar(self.groupBox_28)
        self.horizontalScrollBar_Image_Imax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Image_Imax.setObjectName("horizontalScrollBar_Image_Imax")
        self.verticalLayout_27.addWidget(self.horizontalScrollBar_Image_Imax)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_42 = QtWidgets.QLabel(self.groupBox_28)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_43.addWidget(self.label_42)
        self.label_44 = QtWidgets.QLabel(self.groupBox_28)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_43.addWidget(self.label_44)
        self.verticalLayout_27.addLayout(self.horizontalLayout_43)
        self.gridLayout_16.addLayout(self.verticalLayout_27, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_28, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 3, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalScrollBar_XY = QtWidgets.QScrollBar(self.groupBox_2)
        self.horizontalScrollBar_XY.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_XY.setObjectName("horizontalScrollBar_XY")
        self.gridLayout_3.addWidget(self.horizontalScrollBar_XY, 1, 0, 1, 1)
        self.visWidget_XY = QtWidgets.QOpenGLWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visWidget_XY.sizePolicy().hasHeightForWidth())
        self.visWidget_XY.setSizePolicy(sizePolicy)
        self.visWidget_XY.setObjectName("visWidget_XY")
        self.gridLayout_3.addWidget(self.visWidget_XY, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.visWidget_XZ = QtWidgets.QOpenGLWidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visWidget_XZ.sizePolicy().hasHeightForWidth())
        self.visWidget_XZ.setSizePolicy(sizePolicy)
        self.visWidget_XZ.setObjectName("visWidget_XZ")
        self.gridLayout_5.addWidget(self.visWidget_XZ, 0, 0, 1, 1)
        self.horizontalScrollBar_XZ = QtWidgets.QScrollBar(self.groupBox_8)
        self.horizontalScrollBar_XZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_XZ.setObjectName("horizontalScrollBar_XZ")
        self.gridLayout_5.addWidget(self.horizontalScrollBar_XZ, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.visWidget_YZ = QtWidgets.QOpenGLWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visWidget_YZ.sizePolicy().hasHeightForWidth())
        self.visWidget_YZ.setSizePolicy(sizePolicy)
        self.visWidget_YZ.setObjectName("visWidget_YZ")
        self.gridLayout_2.addWidget(self.visWidget_YZ, 0, 1, 1, 1)
        self.horizontalScrollBar_YZ = QtWidgets.QScrollBar(self.groupBox)
        self.horizontalScrollBar_YZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_YZ.setObjectName("horizontalScrollBar_YZ")
        self.gridLayout_2.addWidget(self.horizontalScrollBar_YZ, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 3, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.visWidget_3D = QtWidgets.QOpenGLWidget(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visWidget_3D.sizePolicy().hasHeightForWidth())
        self.visWidget_3D.setSizePolicy(sizePolicy)
        self.visWidget_3D.setObjectName("visWidget_3D")
        self.gridLayout_6.addWidget(self.visWidget_3D, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_9, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_10, 0, 2, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_27.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_27.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_27, 1, 0, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_12.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_pathFolderWriteResults = QtWidgets.QPushButton(self.tab)
        self.pushButton_pathFolderWriteResults.setObjectName("pushButton_pathFolderWriteResults")
        self.gridLayout_12.addWidget(self.pushButton_pathFolderWriteResults, 2, 0, 1, 1)
        self.pushButton_pathFolderReadImage = QtWidgets.QPushButton(self.tab)
        self.pushButton_pathFolderReadImage.setObjectName("pushButton_pathFolderReadImage")
        self.gridLayout_12.addWidget(self.pushButton_pathFolderReadImage, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_Visualize = QtWidgets.QWidget()
        self.tab_Visualize.setObjectName("tab_Visualize")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Visualize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_Visualize)
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_17.addWidget(self.radioButton_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_18.addWidget(self.radioButton_6)
        self.label_6 = QtWidgets.QLabel(self.groupBox_21)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_21)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_18.addWidget(self.spinBox_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.gridLayout_7.addWidget(self.groupBox_21, 5, 0, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_Visualize)
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_16.addWidget(self.label_35)
        self.label_dimX_VisOut = QtWidgets.QLabel(self.groupBox_7)
        self.label_dimX_VisOut.setObjectName("label_dimX_VisOut")
        self.horizontalLayout_16.addWidget(self.label_dimX_VisOut)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_19.addWidget(self.label_37)
        self.label_dimY_VisOut = QtWidgets.QLabel(self.groupBox_7)
        self.label_dimY_VisOut.setObjectName("label_dimY_VisOut")
        self.horizontalLayout_19.addWidget(self.label_dimY_VisOut)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.label_dimZ_VisOut = QtWidgets.QLabel(self.groupBox_7)
        self.label_dimZ_VisOut.setObjectName("label_dimZ_VisOut")
        self.horizontalLayout_20.addWidget(self.label_dimZ_VisOut)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_26.addWidget(self.groupBox_7)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_41 = QtWidgets.QLabel(self.groupBox_19)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_21.addWidget(self.label_41)
        self.label_bitDepth_VisOut = QtWidgets.QLabel(self.groupBox_19)
        self.label_bitDepth_VisOut.setObjectName("label_bitDepth_VisOut")
        self.horizontalLayout_21.addWidget(self.label_bitDepth_VisOut)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_43 = QtWidgets.QLabel(self.groupBox_19)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_22.addWidget(self.label_43)
        self.label_fileExtension_VisOut = QtWidgets.QLabel(self.groupBox_19)
        self.label_fileExtension_VisOut.setObjectName("label_fileExtension_VisOut")
        self.horizontalLayout_22.addWidget(self.label_fileExtension_VisOut)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_45 = QtWidgets.QLabel(self.groupBox_19)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_23.addWidget(self.label_45)
        self.label_memSize_VisOut = QtWidgets.QLabel(self.groupBox_19)
        self.label_memSize_VisOut.setObjectName("label_memSize_VisOut")
        self.horizontalLayout_23.addWidget(self.label_memSize_VisOut)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_26.addWidget(self.groupBox_19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.gridLayout_7.addWidget(self.groupBox_23, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_Visualize)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.doubleSpinBox_voxelSizeX_VisIn = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeX_VisIn.setObjectName("doubleSpinBox_voxelSizeX_VisIn")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_voxelSizeX_VisIn)
        self.doubleSpinBox_voxelSizeY_VisIn = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeY_VisIn.setObjectName("doubleSpinBox_voxelSizeY_VisIn")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_voxelSizeY_VisIn)
        self.doubleSpinBox_voxelSizeZ_VisIn = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeZ_VisIn.setObjectName("doubleSpinBox_voxelSizeZ_VisIn")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_voxelSizeZ_VisIn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.doubleSpinBox_voxelSizeX_VisOut = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeX_VisOut.setObjectName("doubleSpinBox_voxelSizeX_VisOut")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_voxelSizeX_VisOut)
        self.doubleSpinBox_voxelSizeY_VisOut = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeY_VisOut.setObjectName("doubleSpinBox_voxelSizeY_VisOut")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_voxelSizeY_VisOut)
        self.doubleSpinBox_voxelSizeZ_VisOut = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_voxelSizeZ_VisOut.setObjectName("doubleSpinBox_voxelSizeZ_VisOut")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_voxelSizeZ_VisOut)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_7.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_Visualize)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.label_dimX_VisIn = QtWidgets.QLabel(self.groupBox_6)
        self.label_dimX_VisIn.setObjectName("label_dimX_VisIn")
        self.horizontalLayout_5.addWidget(self.label_dimX_VisIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.label_dimY_VisIn = QtWidgets.QLabel(self.groupBox_6)
        self.label_dimY_VisIn.setObjectName("label_dimY_VisIn")
        self.horizontalLayout_11.addWidget(self.label_dimY_VisIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.label_dimZ_VisIn = QtWidgets.QLabel(self.groupBox_6)
        self.label_dimZ_VisIn.setObjectName("label_dimZ_VisIn")
        self.horizontalLayout_12.addWidget(self.label_dimZ_VisIn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_24.addWidget(self.groupBox_6)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_31 = QtWidgets.QLabel(self.groupBox_18)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_13.addWidget(self.label_31)
        self.label_bitDepth_VisIn = QtWidgets.QLabel(self.groupBox_18)
        self.label_bitDepth_VisIn.setObjectName("label_bitDepth_VisIn")
        self.horizontalLayout_13.addWidget(self.label_bitDepth_VisIn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_26 = QtWidgets.QLabel(self.groupBox_18)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.label_fileExtension_VisIn = QtWidgets.QLabel(self.groupBox_18)
        self.label_fileExtension_VisIn.setObjectName("label_fileExtension_VisIn")
        self.horizontalLayout_14.addWidget(self.label_fileExtension_VisIn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_30 = QtWidgets.QLabel(self.groupBox_18)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.label_memSize_VisIn = QtWidgets.QLabel(self.groupBox_18)
        self.label_memSize_VisIn.setObjectName("label_memSize_VisIn")
        self.horizontalLayout_15.addWidget(self.label_memSize_VisIn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_24.addWidget(self.groupBox_18)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.gridLayout_7.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab_Visualize)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_7.addWidget(self.progressBar, 8, 0, 1, 1)
        self.pushButton_computeResampledImage = QtWidgets.QPushButton(self.tab_Visualize)
        self.pushButton_computeResampledImage.setObjectName("pushButton_computeResampledImage")
        self.gridLayout_7.addWidget(self.pushButton_computeResampledImage, 7, 0, 1, 1)
        self.pushButton_displayResampledImage = QtWidgets.QPushButton(self.tab_Visualize)
        self.pushButton_displayResampledImage.setObjectName("pushButton_displayResampledImage")
        self.gridLayout_7.addWidget(self.pushButton_displayResampledImage, 9, 0, 1, 1)
        self.pushButton_checkVisOut = QtWidgets.QPushButton(self.tab_Visualize)
        self.pushButton_checkVisOut.setObjectName("pushButton_checkVisOut")
        self.gridLayout_7.addWidget(self.pushButton_checkVisOut, 3, 0, 1, 1)
        self.pushButton_saveSettingsVisualize = QtWidgets.QPushButton(self.tab_Visualize)
        self.pushButton_saveSettingsVisualize.setObjectName("pushButton_saveSettingsVisualize")
        self.gridLayout_7.addWidget(self.pushButton_saveSettingsVisualize, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 10, 0, 1, 1)
        self.pushButton_checkVisIn = QtWidgets.QPushButton(self.tab_Visualize)
        self.pushButton_checkVisIn.setObjectName("pushButton_checkVisIn")
        self.gridLayout_7.addWidget(self.pushButton_checkVisIn, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Visualize, "")
        self.tab_Select = QtWidgets.QWidget()
        self.tab_Select.setObjectName("tab_Select")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_Select)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_Select)
        self.groupBox_22.setObjectName("groupBox_22")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_22)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_22)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_selectStartX = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStartX.setMaximum(999999)
        self.spinBox_selectStartX.setObjectName("spinBox_selectStartX")
        self.horizontalLayout_6.addWidget(self.spinBox_selectStartX)
        self.spinBox_selectStartY = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStartY.setMaximum(999999)
        self.spinBox_selectStartY.setObjectName("spinBox_selectStartY")
        self.horizontalLayout_6.addWidget(self.spinBox_selectStartY)
        self.spinBox_selectStartZ = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStartZ.setMaximum(999999)
        self.spinBox_selectStartZ.setObjectName("spinBox_selectStartZ")
        self.horizontalLayout_6.addWidget(self.spinBox_selectStartZ)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_10 = QtWidgets.QLabel(self.groupBox_22)
        self.label_10.setObjectName("label_10")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinBox_selectStopX = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStopX.setMaximum(999999)
        self.spinBox_selectStopX.setObjectName("spinBox_selectStopX")
        self.horizontalLayout_7.addWidget(self.spinBox_selectStopX)
        self.spinBox_selectStopY = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStopY.setMaximum(999999)
        self.spinBox_selectStopY.setObjectName("spinBox_selectStopY")
        self.horizontalLayout_7.addWidget(self.spinBox_selectStopY)
        self.spinBox_selectStopZ = QtWidgets.QSpinBox(self.groupBox_22)
        self.spinBox_selectStopZ.setMaximum(999999)
        self.spinBox_selectStopZ.setObjectName("spinBox_selectStopZ")
        self.horizontalLayout_7.addWidget(self.spinBox_selectStopZ)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.groupBox_22)
        self.pushButton_cropImage = QtWidgets.QPushButton(self.tab_Select)
        self.pushButton_cropImage.setObjectName("pushButton_cropImage")
        self.verticalLayout_5.addWidget(self.pushButton_cropImage)
        self.pushButton_uncropImage = QtWidgets.QPushButton(self.tab_Select)
        self.pushButton_uncropImage.setObjectName("pushButton_uncropImage")
        self.verticalLayout_5.addWidget(self.pushButton_uncropImage)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_Select, "")
        self.tab_Detect = QtWidgets.QWidget()
        self.tab_Detect.setObjectName("tab_Detect")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_Detect)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_16 = QtWidgets.QLabel(self.groupBox_20)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_28.addWidget(self.label_16)
        self.doubleSpinBox_voxelSizeX_DetIn = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeX_DetIn.setObjectName("doubleSpinBox_voxelSizeX_DetIn")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_voxelSizeX_DetIn)
        self.doubleSpinBox_voxelSizeY_DetIn = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeY_DetIn.setObjectName("doubleSpinBox_voxelSizeY_DetIn")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_voxelSizeY_DetIn)
        self.doubleSpinBox_voxelSizeZ_DetIn = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeZ_DetIn.setObjectName("doubleSpinBox_voxelSizeZ_DetIn")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_voxelSizeZ_DetIn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.groupBox_20)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_29.addWidget(self.label_17)
        self.doubleSpinBox_voxelSizeX_DetOut = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeX_DetOut.setObjectName("doubleSpinBox_voxelSizeX_DetOut")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_voxelSizeX_DetOut)
        self.doubleSpinBox_voxelSizeY_DetOut = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeY_DetOut.setObjectName("doubleSpinBox_voxelSizeY_DetOut")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_voxelSizeY_DetOut)
        self.doubleSpinBox_voxelSizeZ_DetOut = QtWidgets.QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_voxelSizeZ_DetOut.setObjectName("doubleSpinBox_voxelSizeZ_DetOut")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_voxelSizeZ_DetOut)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.verticalLayout_15.addWidget(self.groupBox_20)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_14)
        self.label_11.setObjectName("label_11")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_cellRadiusMin = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_cellRadiusMin.setObjectName("spinBox_cellRadiusMin")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_cellRadiusMin)
        self.horizontalLayout_9.addLayout(self.formLayout_8)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_14)
        self.label_12.setObjectName("label_12")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_cellRadiusMax = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_cellRadiusMax.setObjectName("spinBox_cellRadiusMax")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_cellRadiusMax)
        self.horizontalLayout_9.addLayout(self.formLayout_9)
        self.verticalLayout_15.addWidget(self.groupBox_14)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_15 = QtWidgets.QLabel(self.groupBox_17)
        self.label_15.setObjectName("label_15")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.spinBox_nScales = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_nScales.setObjectName("spinBox_nScales")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_nScales)
        self.verticalLayout_12.addLayout(self.formLayout_11)
        self.verticalLayout_15.addWidget(self.groupBox_17)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinBox_computingCubeSize = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_computingCubeSize.setObjectName("spinBox_computingCubeSize")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_computingCubeSize)
        self.horizontalLayout_33.addLayout(self.formLayout_10)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.spinBox_computingCubeOverlap = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_computingCubeOverlap.setObjectName("spinBox_computingCubeOverlap")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_computingCubeOverlap)
        self.label_14 = QtWidgets.QLabel(self.groupBox_16)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_33.addLayout(self.formLayout_5)
        self.verticalLayout_16.addLayout(self.horizontalLayout_33)
        self.verticalLayout_15.addWidget(self.groupBox_16)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_TensorOff = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_TensorOff.setObjectName("radioButton_TensorOff")
        self.horizontalLayout.addWidget(self.radioButton_TensorOff)
        self.radioButton_TensorOn = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_TensorOn.setChecked(True)
        self.radioButton_TensorOn.setObjectName("radioButton_TensorOn")
        self.horizontalLayout.addWidget(self.radioButton_TensorOn)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.verticalLayout_15.addWidget(self.groupBox_3)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_24.setObjectName("groupBox_24")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_24)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_7 = QtWidgets.QLabel(self.groupBox_24)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_31.addWidget(self.label_7)
        self.spinBox_nProcess = QtWidgets.QSpinBox(self.groupBox_24)
        self.spinBox_nProcess.setObjectName("spinBox_nProcess")
        self.horizontalLayout_31.addWidget(self.spinBox_nProcess)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.verticalLayout_15.addWidget(self.groupBox_24)
        self.pushButton_checkDet = QtWidgets.QPushButton(self.tab_Detect)
        self.pushButton_checkDet.setObjectName("pushButton_checkDet")
        self.verticalLayout_15.addWidget(self.pushButton_checkDet)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_Detect)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.label_cubeInSize_px = QtWidgets.QLabel(self.groupBox_12)
        self.label_cubeInSize_px.setObjectName("label_cubeInSize_px")
        self.horizontalLayout_10.addWidget(self.label_cubeInSize_px)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_36.addWidget(self.label_29)
        self.label_cubeOutSize_px = QtWidgets.QLabel(self.groupBox_12)
        self.label_cubeOutSize_px.setObjectName("label_cubeOutSize_px")
        self.horizontalLayout_36.addWidget(self.label_cubeOutSize_px)
        self.verticalLayout_14.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_32 = QtWidgets.QLabel(self.groupBox_12)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_37.addWidget(self.label_32)
        self.label_nCubes = QtWidgets.QLabel(self.groupBox_12)
        self.label_nCubes.setObjectName("label_nCubes")
        self.horizontalLayout_37.addWidget(self.label_nCubes)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_12)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_DetRAM = QtWidgets.QLabel(self.groupBox_12)
        self.label_DetRAM.setObjectName("label_DetRAM")
        self.horizontalLayout_4.addWidget(self.label_DetRAM)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.label_DetCPU = QtWidgets.QLabel(self.groupBox_12)
        self.label_DetCPU.setObjectName("label_DetCPU")
        self.horizontalLayout_8.addWidget(self.label_DetCPU)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_21 = QtWidgets.QLabel(self.groupBox_12)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_32.addWidget(self.label_21)
        self.label_DetTime = QtWidgets.QLabel(self.groupBox_12)
        self.label_DetTime.setObjectName("label_DetTime")
        self.horizontalLayout_32.addWidget(self.label_DetTime)
        self.verticalLayout_14.addLayout(self.horizontalLayout_32)
        self.verticalLayout_15.addWidget(self.groupBox_12)
        self.pushButton_saveSettingsDetect = QtWidgets.QPushButton(self.tab_Detect)
        self.pushButton_saveSettingsDetect.setObjectName("pushButton_saveSettingsDetect")
        self.verticalLayout_15.addWidget(self.pushButton_saveSettingsDetect)
        self.pushButton_computeDetections = QtWidgets.QPushButton(self.tab_Detect)
        self.pushButton_computeDetections.setObjectName("pushButton_computeDetections")
        self.verticalLayout_15.addWidget(self.pushButton_computeDetections)
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_Detect)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_15.addWidget(self.progressBar_2)
        self.pushButton_displayDetections = QtWidgets.QPushButton(self.tab_Detect)
        self.pushButton_displayDetections.setObjectName("pushButton_displayDetections")
        self.verticalLayout_15.addWidget(self.pushButton_displayDetections)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_Detect, "")
        self.tab_Filter = QtWidgets.QWidget()
        self.tab_Filter.setObjectName("tab_Filter")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_Filter)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_Filter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalScrollBar_Rmin = QtWidgets.QScrollBar(self.groupBox_11)
        self.horizontalScrollBar_Rmin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Rmin.setObjectName("horizontalScrollBar_Rmin")
        self.verticalLayout_17.addWidget(self.horizontalScrollBar_Rmin)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_5 = QtWidgets.QLabel(self.groupBox_11)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_30.addWidget(self.label_5)
        self.label_Rmin = QtWidgets.QLabel(self.groupBox_11)
        self.label_Rmin.setObjectName("label_Rmin")
        self.horizontalLayout_30.addWidget(self.label_Rmin)
        self.verticalLayout_17.addLayout(self.horizontalLayout_30)
        self.gridLayout_4.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalScrollBar_Rmax = QtWidgets.QScrollBar(self.groupBox_11)
        self.horizontalScrollBar_Rmax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Rmax.setObjectName("horizontalScrollBar_Rmax")
        self.verticalLayout_18.addWidget(self.horizontalScrollBar_Rmax)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_25.addWidget(self.label_20)
        self.label_Rmax = QtWidgets.QLabel(self.groupBox_11)
        self.label_Rmax.setObjectName("label_Rmax")
        self.horizontalLayout_25.addWidget(self.label_Rmax)
        self.verticalLayout_18.addLayout(self.horizontalLayout_25)
        self.gridLayout_4.addLayout(self.verticalLayout_18, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_Filter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalScrollBar_Imin = QtWidgets.QScrollBar(self.groupBox_13)
        self.horizontalScrollBar_Imin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Imin.setObjectName("horizontalScrollBar_Imin")
        self.verticalLayout_19.addWidget(self.horizontalScrollBar_Imin)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_27 = QtWidgets.QLabel(self.groupBox_13)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_34.addWidget(self.label_27)
        self.label_Imin = QtWidgets.QLabel(self.groupBox_13)
        self.label_Imin.setObjectName("label_Imin")
        self.horizontalLayout_34.addWidget(self.label_Imin)
        self.verticalLayout_19.addLayout(self.horizontalLayout_34)
        self.gridLayout_11.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalScrollBar_Imax = QtWidgets.QScrollBar(self.groupBox_13)
        self.horizontalScrollBar_Imax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Imax.setObjectName("horizontalScrollBar_Imax")
        self.verticalLayout_20.addWidget(self.horizontalScrollBar_Imax)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_28 = QtWidgets.QLabel(self.groupBox_13)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_35.addWidget(self.label_28)
        self.label_Imax = QtWidgets.QLabel(self.groupBox_13)
        self.label_Imax.setObjectName("label_Imax")
        self.horizontalLayout_35.addWidget(self.label_Imax)
        self.verticalLayout_20.addLayout(self.horizontalLayout_35)
        self.gridLayout_11.addLayout(self.verticalLayout_20, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_13, 3, 0, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_Filter)
        self.groupBox_27.setObjectName("groupBox_27")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_27)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalScrollBar_Gmax = QtWidgets.QScrollBar(self.groupBox_27)
        self.horizontalScrollBar_Gmax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Gmax.setObjectName("horizontalScrollBar_Gmax")
        self.verticalLayout_25.addWidget(self.horizontalScrollBar_Gmax)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_40 = QtWidgets.QLabel(self.groupBox_27)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_41.addWidget(self.label_40)
        self.label_Gmax = QtWidgets.QLabel(self.groupBox_27)
        self.label_Gmax.setObjectName("label_Gmax")
        self.horizontalLayout_41.addWidget(self.label_Gmax)
        self.verticalLayout_25.addLayout(self.horizontalLayout_41)
        self.gridLayout_15.addLayout(self.verticalLayout_25, 3, 0, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalScrollBar_Gmin = QtWidgets.QScrollBar(self.groupBox_27)
        self.horizontalScrollBar_Gmin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Gmin.setObjectName("horizontalScrollBar_Gmin")
        self.verticalLayout_24.addWidget(self.horizontalScrollBar_Gmin)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_36 = QtWidgets.QLabel(self.groupBox_27)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_40.addWidget(self.label_36)
        self.label_Gmin = QtWidgets.QLabel(self.groupBox_27)
        self.label_Gmin.setObjectName("label_Gmin")
        self.horizontalLayout_40.addWidget(self.label_Gmin)
        self.verticalLayout_24.addLayout(self.horizontalLayout_40)
        self.gridLayout_15.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_27, 4, 0, 1, 1)
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_Filter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_26)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalScrollBar_Nmin = QtWidgets.QScrollBar(self.groupBox_26)
        self.horizontalScrollBar_Nmin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Nmin.setObjectName("horizontalScrollBar_Nmin")
        self.verticalLayout_22.addWidget(self.horizontalScrollBar_Nmin)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_18 = QtWidgets.QLabel(self.groupBox_26)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_38.addWidget(self.label_18)
        self.label_Nmin = QtWidgets.QLabel(self.groupBox_26)
        self.label_Nmin.setObjectName("label_Nmin")
        self.horizontalLayout_38.addWidget(self.label_Nmin)
        self.verticalLayout_22.addLayout(self.horizontalLayout_38)
        self.gridLayout_14.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalScrollBar_Nmax = QtWidgets.QScrollBar(self.groupBox_26)
        self.horizontalScrollBar_Nmax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Nmax.setObjectName("horizontalScrollBar_Nmax")
        self.verticalLayout_23.addWidget(self.horizontalScrollBar_Nmax)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_34 = QtWidgets.QLabel(self.groupBox_26)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_39.addWidget(self.label_34)
        self.label_Nmax = QtWidgets.QLabel(self.groupBox_26)
        self.label_Nmax.setObjectName("label_Nmax")
        self.horizontalLayout_39.addWidget(self.label_Nmax)
        self.verticalLayout_23.addLayout(self.horizontalLayout_39)
        self.gridLayout_14.addLayout(self.verticalLayout_23, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_26, 2, 0, 1, 1)
        self.pushButton_checkFilters = QtWidgets.QPushButton(self.tab_Filter)
        self.pushButton_checkFilters.setObjectName("pushButton_checkFilters")
        self.gridLayout_9.addWidget(self.pushButton_checkFilters, 0, 0, 1, 1)
        self.pushButton_applyFilters = QtWidgets.QPushButton(self.tab_Filter)
        self.pushButton_applyFilters.setObjectName("pushButton_applyFilters")
        self.gridLayout_9.addWidget(self.pushButton_applyFilters, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Filter, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_displayTable = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_displayTable.setObjectName("pushButton_displayTable")
        self.verticalLayout_21.addWidget(self.pushButton_displayTable)
        self.tableView = QtWidgets.QTableView(self.groupBox_15)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_21.addWidget(self.tableView)
        self.gridLayout_10.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.groupBox_28.setTitle(_translate("MainWindow", "I"))
        self.label_33.setText(_translate("MainWindow", "Min"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.label_42.setText(_translate("MainWindow", "Max"))
        self.label_44.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Objects"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Visualization"))
        self.groupBox_2.setTitle(_translate("MainWindow", "XY"))
        self.groupBox_8.setTitle(_translate("MainWindow", "XZ"))
        self.groupBox.setTitle(_translate("MainWindow", "YZ"))
        self.groupBox_9.setTitle(_translate("MainWindow", "3D"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Load a Project"))
        self.pushButton_pathFolderWriteResults.setText(_translate("MainWindow", "Select Save Folder"))
        self.pushButton_pathFolderReadImage.setText(_translate("MainWindow", "Select Image Folder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Import"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Computing Settings"))
        self.radioButton_5.setText(_translate("MainWindow", "Serial"))
        self.radioButton_6.setText(_translate("MainWindow", "Parallel"))
        self.label_6.setText(_translate("MainWindow", "nProcesses"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Output Image Information"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Dimensions [pixels]"))
        self.label_35.setText(_translate("MainWindow", "nx:"))
        self.label_dimX_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_37.setText(_translate("MainWindow", "ny:"))
        self.label_dimY_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_39.setText(_translate("MainWindow", "nz:"))
        self.label_dimZ_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Information"))
        self.label_41.setText(_translate("MainWindow", "nBits:"))
        self.label_bitDepth_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_43.setText(_translate("MainWindow", "Format:"))
        self.label_fileExtension_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "Size [Gb]:"))
        self.label_memSize_VisOut.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ReSampling: Voxel Size [um]"))
        self.label_2.setText(_translate("MainWindow", "In"))
        self.label_4.setText(_translate("MainWindow", "Out"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Input Image Information"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Dimensions [pixels]"))
        self.label_23.setText(_translate("MainWindow", "nx:"))
        self.label_dimX_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "ny:"))
        self.label_dimY_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "nz:"))
        self.label_dimZ_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Information"))
        self.label_31.setText(_translate("MainWindow", "nBits:"))
        self.label_bitDepth_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "Format:"))
        self.label_fileExtension_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "Size [Gb]:"))
        self.label_memSize_VisIn.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_computeResampledImage.setText(_translate("MainWindow", "Compute ReSampled Image"))
        self.pushButton_displayResampledImage.setText(_translate("MainWindow", "Display Resampled Image"))
        self.pushButton_checkVisOut.setText(_translate("MainWindow", "Check Output"))
        self.pushButton_saveSettingsVisualize.setText(_translate("MainWindow", "Save Visualize Settings"))
        self.pushButton_checkVisIn.setText(_translate("MainWindow", "Check Input"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Visualize), _translate("MainWindow", "Visualize"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Select ROI"))
        self.label_9.setText(_translate("MainWindow", "Start"))
        self.label_10.setText(_translate("MainWindow", "End"))
        self.pushButton_cropImage.setText(_translate("MainWindow", "Crop"))
        self.pushButton_uncropImage.setText(_translate("MainWindow", "UnCrop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Select), _translate("MainWindow", "Select"))
        self.groupBox_20.setTitle(_translate("MainWindow", "DownSampling: Voxel Size [um]"))
        self.label_16.setText(_translate("MainWindow", "In"))
        self.label_17.setText(_translate("MainWindow", "Out"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Radius Range [um]"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_12.setText(_translate("MainWindow", "Max"))
        self.groupBox_17.setTitle(_translate("MainWindow", "MultiScale"))
        self.label_15.setText(_translate("MainWindow", "nScales"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Split Volume: Cube Size [um]"))
        self.label_13.setText(_translate("MainWindow", "Size"))
        self.label_14.setText(_translate("MainWindow", "Overlap"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tensor Computation"))
        self.radioButton_TensorOff.setText(_translate("MainWindow", "No"))
        self.radioButton_TensorOn.setText(_translate("MainWindow", "Yes"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Computing Settings"))
        self.label_7.setText(_translate("MainWindow", "nProcesses"))
        self.pushButton_checkDet.setText(_translate("MainWindow", "Check Computing Resources"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Required Resources "))
        self.label_22.setText(_translate("MainWindow", "cubeInSize:"))
        self.label_cubeInSize_px.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "cubeOutSize:"))
        self.label_cubeOutSize_px.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "nCubes:"))
        self.label_nCubes.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "RAM:"))
        self.label_DetRAM.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "CPU:"))
        self.label_DetCPU.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "Time:"))
        self.label_DetTime.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_saveSettingsDetect.setText(_translate("MainWindow", "Save Detect Settings"))
        self.pushButton_computeDetections.setText(_translate("MainWindow", "Compute Detections"))
        self.pushButton_displayDetections.setText(_translate("MainWindow", "Display Detections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Detect), _translate("MainWindow", "Detect"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Radius [um]"))
        self.label_5.setText(_translate("MainWindow", "Min"))
        self.label_Rmin.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "Max"))
        self.label_Rmax.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_13.setTitle(_translate("MainWindow", "I_raw"))
        self.label_27.setText(_translate("MainWindow", "Min"))
        self.label_Imin.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "Max"))
        self.label_Imax.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Gain"))
        self.label_40.setText(_translate("MainWindow", "Max"))
        self.label_Gmax.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "Min"))
        self.label_Gmin.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_26.setTitle(_translate("MainWindow", "nScales"))
        self.label_18.setText(_translate("MainWindow", "Min"))
        self.label_Nmin.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "Max"))
        self.label_Nmax.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_checkFilters.setText(_translate("MainWindow", "Check Filters"))
        self.pushButton_applyFilters.setText(_translate("MainWindow", "Apply Filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Filter), _translate("MainWindow", "Filter"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Explore Results"))
        self.pushButton_displayTable.setText(_translate("MainWindow", "Display Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Validate"))

